// Categories resource
const GET_CATEGORIES_LOADING = "api/GET_CATEGORIES_LOADING";
const GET_CATEGORIES_SUCESS = "api/GET_CATEGORIES_SUCESS";
const GET_CATEGORIES_ERROR = "api/GET_CATEGORIES_ERROR";

const GET_CATEGORY_POSTS_LOADING = "api/GET_CATEGORY_POSTS_LOADING";
const GET_CATEGORY_POSTS_SUCCESS = "api/GET_CATEGORY_POSTS_SUCCESS";
const GET_CATEGORY_POSTS_ERROR = "api/GET_CATEGORY_POSTS_ERROR";

// Posts resorce
const GET_POSTS_LOADING = "api/GET_POSTS_LOADING";
const GET_POSTS_SUCCESS = "api/GET_POSTS_SUCCESS";
const GET_POSTS_ERROR = "api/GET_POSTS_ERROR";

const POST_POST_LOADING = "api/POST_POST_LOADING";
const POST_POST_SUCCESS = "api/POST_POST_SUCCESS";
const POST_POST_ERROR = "api/POST_POST_ERROR";

const GET_POST_LOADING = "api/GET_POST_LOADING";
const GET_POST_SUCCESS = "api/GET_POST_SUCCESS";
const GET_POST_ERROR = "api/GET_POST_ERROR";

const POST_POST_VOTE_LOADING = "api/POST_POST_VOTE_LOADING";
const POST_POST_VOTE_SUCCESS = "api/POST_POST_VOTE_SUCCESS";
const POST_POST_VOTE_ERROR = "api/POST_POST_VOTE_ERROR";

const PUT_POST_DETAILS_LOADING = "api/PUT_POST_DETAILS_LOADING";
const PUT_POST_DETAILS_SUCCESS = "api/PUT_POST_DETAILS_SUCCESS";
const PUT_POST_DETAILS_ERROR = "api/PUT_POST_DETAILS_ERROR";

const DELETE_POST_LOADING = "api/DELETE_POST_LOADING";
const DELETE_POST_SUCCESS = "api/DELETE_POST_SUCCESS";
const DELETE_POST_ERROR = "api/DELETE_POST_ERROR";

const GET_POST_COMMENTS_LOADING = "api/GET_POST_COMMENTS_LOADING";
const GET_POST_COMMENTS_SUCCESS = "api/GET_POST_COMMENTS_SUCCESS";
const GET_POST_COMMENTS_ERROR = "api/GET_POST_COMMENTS_ERROR";

// Comments resource
const GET_COMMENT_LOADING = "api/GET_COMMENT_LOADING";
const GET_COMMENT_SUCCESS = "api/GET_COMMENT_SUCCESS";
const GET_COMMENT_ERROR = "api/GET_COMMENT_ERROR";

const POST_COMMENT_VOTE_LOADING = "api/POST_COMMENT_VOTE_LOADING";
const POST_COMMENT_VOTE_SUCCESS = "api/POST_COMMENT_VOTE_SUCCESS";
const POST_COMMENT_VOTE_ERROR = "api/POST_COMMENT_VOTE_ERROR";

const PUT_COMMENT_DETAILS_LOADING = "api/PUT_COMMENT_DETAILS_LOADING";
const PUT_COMMENT_DETAILS_SUCCESS = "api/PUT_COMMENT_DETAILS_SUCCESS";
const PUT_COMMENT_DETAILS_ERROR = "api/PUT_COMMENT_DETAILS_ERROR";

const DELETE_COMMENT_LOADING = "api/DELETE_COMMENT_LOADING";
const DELETE_COMMENT_SUCCESS = "api/DELETE_COMMENT_SUCCESS";
const DELETE_COMMENT_ERROR = "api/DELETE_COMMENT_ERROR";

export {
  GET_CATEGORIES_LOADING,
  GET_CATEGORIES_SUCESS,
  GET_CATEGORIES_ERROR,
  GET_CATEGORY_POSTS_LOADING,
  GET_CATEGORY_POSTS_ERROR,
  GET_CATEGORY_POSTS_SUCCESS,
  GET_POSTS_LOADING,
  GET_POSTS_SUCCESS,
  GET_POSTS_ERROR,
  POST_POST_LOADING,
  POST_POST_SUCCESS,
  POST_POST_ERROR,
  GET_POST_LOADING,
  GET_POST_SUCCESS,
  GET_POST_ERROR,
  POST_POST_VOTE_LOADING,
  POST_POST_VOTE_SUCCESS,
  POST_POST_VOTE_ERROR,
  PUT_POST_DETAILS_LOADING,
  PUT_POST_DETAILS_SUCCESS,
  PUT_POST_DETAILS_ERROR,
  DELETE_POST_LOADING,
  DELETE_POST_SUCCESS,
  DELETE_POST_ERROR,
  GET_POST_COMMENTS_LOADING,
  GET_POST_COMMENTS_SUCCESS,
  GET_POST_COMMENTS_ERROR,
  GET_COMMENT_LOADING,
  GET_COMMENT_SUCCESS,
  GET_COMMENT_ERROR,
  POST_COMMENT_VOTE_LOADING,
  POST_COMMENT_VOTE_SUCCESS,
  POST_COMMENT_VOTE_ERROR,
  PUT_COMMENT_DETAILS_LOADING,
  PUT_COMMENT_DETAILS_SUCCESS,
  PUT_COMMENT_DETAILS_ERROR,
  DELETE_COMMENT_LOADING,
  DELETE_COMMENT_SUCCESS,
  DELETE_COMMENT_ERROR
};
